### ISSUE TITLE
Cannot nest multipart messages

### ISSUE THREAD

**Issue by alltom** [sloonz/go-mime-message#2]
When trying to pass a `MultipartMessage` to `AddPart`:

    cannot use body (type *message.MultipartMessage) as type *message.Message in function argument

Would be useful for sending text and HTML versions of a message, with attachments:

    multipart/related
      multipart/alternative
        text/plain
        text/html
      image/png

as described at: http://code.activestate.com/recipes/473810-send-an-html-email-with-embedded-image-and-plain-t/

**Comment by sloonz** [comment]
`msgRelated.AddPart(&msgAlternative.Message)` should do the job
