### ISSUE TITLE
Headers not written for multipart messages

### ISSUE THREAD

**Issue by alltom** [sloonz/go-mime-message#3]
`MultipartMessage` takes responsibility for printing each `Message`'s headers before their bodies, but there ought to be a way to write a `MultipartMessage` with its headers, too. Reading from `Body` doesn't do the trick (though it probably shouldn't):

    msg := mimeMessage.NewMultipartMessage("related", randomBoundary())
    io.Copy(os.Stdout, msg.Body)

only prints:

    --xxx

instead of:

    Content-Type: multipart/related; boundary="xxx"
    
    --xxx

**Comment by sloonz** [comment]
4 years (didn’t get a notification from github…). Well, in case it’s useful for someone :

You want to do `io.Copy(os.Stdout, msg)` (drop the `.Body` part).

**Comment by alltom** [comment]
Thanks! (I'm still using this library. :)
