### ISSUE TITLE
How to add MultipartMessage as part of another MultipartMessage

### ISSUE THREAD

**Issue by bithavoc** [sloonz/go-mime-message#4]
I need to encode a `multipart/mixed` as part of a `multipart/alternative`, that means a `MultipartMessage` as part of a `MultipartMessage`.

The problem is `MultipartMessage.AddPart` only supports `*Message`.

Is there a way one can convert a `*MultipartMessage` into a `*Message`?

**Comment by sloonz** [comment]
Have you tried the solution in https://github.com/sloonz/go-mime-message/issues/2 ?

**Comment by bithavoc** [comment]
that did the trick, thanks @sloonz great package 🎉
